Repository konstructio/kubefirst, pull requests merged in 2022-10, with the labels that each got.

#490 minor tweaks to intro docs
  docs/index.md
Labels: docs

#543 fix addon viper when addons flag is empty
  internal/flagset/installer.go
Labels: bug

#547 Test init addons
  internal/addon/addon.go
  internal/flagset/github.go
  internal/flagset/init_test.go
  internal/flagset/installer.go
Labels: enhancement
