Repository konstructio/kubefirst, pull requests merged in 2022-08, with the labels that each got.

#177 WIP - feat-support-gh-gitops
  cmd/createGithub.go
Labels: DO-NOT-MERGE

#200 nodes_spot
  cmd/init.go
  internal/terraform/terraform.go
Labels: engineering day

#247 Bug r53 hostedzone notexist
  cmd/init.go
  internal/aws/aws.go
Labels: bug

#226 Simplify create
  cmd/commonFlags.go
  cmd/create.go
  cmd/createGithub.go
  cmd/createGitlab.go
  cmd/githubAdd.go
  cmd/githubAddValidate.go
  cmd/githubPopulate.go
  cmd/githubRemove.go
  cmd/githubRemoveValidate.go
  cmd/init.go
  cmd/kubefirstTemplate.go
  cmd/loadTemplate.go
  configs/config.go
  internal/downloadManager/download.go
  internal/flagset/aws.go
  internal/flagset/github.go
  internal/flagset/global.go
  internal/flagset/installer.go
  internal/gitClient/git.go
Labels: DO-NOT-MERGE
