Repository konstructio/kubefirst, pull requests merged in 2022-12, with the labels that each got.

#854 add developer relations issues automations
  .github/workflows/devrel-automations.yaml
Labels: automation

#910 fix #897 - vouch image for arm/x86 arch
  pkg/helpers.go
Labels: bug

#911 feat: update local destroy to follow new command
  docs/kubefirst/local/destroy.md
  docs/kubefirst/local/faq.md
Labels: docs

#914 added validation on bot password when is gitlab flavor
  internal/flagset/installer.go
Labels: enhancement

#928 fix passwordbot 'and' operator in if
  internal/flagset/installer.go
Labels: bug

#933 fix passwordbot logic - unit test
  internal/flagset/installer.go
Labels: bug

#929 feat: Add retry logic to create ngrok tunnel
  pkg/ngrok.go
  pkg/retry_logic.go
Labels: bug

#944 fix: Include env var for region
  internal/github/github.go
  internal/terraform/terraform.go
Labels: bug, github, aws

#942 update license copyright years
  LICENSE
Labels: docs

#931 first draft of the contributing guide (close #885)
  CONTRIBUTING.md
Labels: docs, community

#960 add v1.11 roadmap (close #802)
  docs/roadmap/index.md
Labels: docs

#977 update checkout action to v3
  .github/workflows/promote-docs-to-prod.yaml
  .github/workflows/publish-docs.yaml
Labels: automation
